import { useState } from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import * as z from 'zod';
import { useAppStore } from '@/store/useAppStore';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Checkbox } from '@/components/ui/checkbox';
import { Slider } from '@/components/ui/slider';
import { Progress } from '@/components/ui/progress';
import { Upload as UploadIcon, FileText, CheckCircle } from 'lucide-react';
import { toast } from 'sonner';
import { useNavigate } from 'react-router-dom';

const uploadSchema = z.object({
  file: z.any().refine((file) => file !== null, 'Please select a file'),
  subject: z.string().min(1, 'Please select a subject'),
  folder: z.string().min(1, 'Please select a folder'),
  createSummary: z.boolean(),
  generateQuiz: z.boolean(),
  quizQuestions: z.number().min(5).max(20),
  quizDifficulty: z.enum(['Easy', 'Medium', 'Hard']),
});

type UploadFormData = z.infer<typeof uploadSchema>;

export default function Upload() {
  const { subjects, addFile, addSummary, addQuiz } = useAppStore();
  const navigate = useNavigate();
  const [selectedFile, setSelectedFile] = useState<File | null>(null);
  const [processing, setProcessing] = useState(false);
  const [progress, setProgress] = useState(0);
  const [completed, setCompleted] = useState(false);

  const {
    register,
    handleSubmit,
    watch,
    setValue,
    formState: { errors },
  } = useForm<UploadFormData>({
    resolver: zodResolver(uploadSchema),
    defaultValues: {
      createSummary: true,
      generateQuiz: false,
      quizQuestions: 10,
      quizDifficulty: 'Medium',
    },
  });

  const selectedSubject = watch('subject');
  const createSummary = watch('createSummary');
  const generateQuiz = watch('generateQuiz');
  const quizQuestions = watch('quizQuestions');

  const subjectFolders = subjects.find((s) => s.name === selectedSubject)?.folders || [];

  const simulateProcessing = async () => {
    setProcessing(true);
    setProgress(0);

    // Simulate file upload
    for (let i = 0; i <= 100; i += 10) {
      await new Promise((resolve) => setTimeout(resolve, 200));
      setProgress(i);
    }

    setProcessing(false);
    setCompleted(true);
    toast.success('File processed successfully!');

    setTimeout(() => {
      navigate('/summaries');
    }, 2000);
  };

  const onSubmit = async (data: UploadFormData) => {
    if (!selectedFile) return;

    const fileId = `file${Date.now()}`;
    const fileName = selectedFile.name;

    // Add file
    addFile({
      id: fileId,
      name: fileName,
      subject: data.subject,
      folder: data.folder,
      uploadDate: new Date().toISOString().split('T')[0],
      size: `${(selectedFile.size / 1024 / 1024).toFixed(1)} MB`,
      summaryCount: data.createSummary ? 1 : 0,
      quizCount: data.generateQuiz ? 1 : 0,
    });

    // Create summary if requested
    if (data.createSummary) {
      addSummary({
        id: `sum${Date.now()}`,
        fileId,
        fileName,
        content: 'AI-generated summary of the uploaded document. This content would be generated by the backend processing system analyzing the document content and extracting key information.',
        keyConcepts: ['Concept 1', 'Concept 2', 'Concept 3', 'Concept 4'],
        createdAt: new Date().toISOString().split('T')[0],
        isImportant: false,
      });
    }

    // Generate quiz if requested
    if (data.generateQuiz) {
      const questions = Array.from({ length: data.quizQuestions }, (_, i) => ({
        id: `q${Date.now()}_${i}`,
        question: `Sample question ${i + 1} based on ${fileName}`,
        options: ['Option A', 'Option B', 'Option C', 'Option D'],
        correctAnswer: Math.floor(Math.random() * 4),
      }));

      addQuiz({
        id: `quiz${Date.now()}`,
        fileId,
        fileName,
        subject: data.subject,
        difficulty: data.quizDifficulty,
        questions,
        createdAt: new Date().toISOString().split('T')[0],
        completed: false,
      });
    }

    await simulateProcessing();
  };

  return (
    <div className="mx-auto max-w-3xl space-y-6">
      <div>
        <h1 className="text-3xl font-bold">Upload File</h1>
        <p className="text-muted-foreground">Upload your study materials and generate AI summaries and quizzes</p>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>File Upload</CardTitle>
        </CardHeader>
        <CardContent>
          <form onSubmit={handleSubmit(onSubmit)} className="space-y-6">
            {/* File Input */}
            <div className="space-y-2">
              <Label htmlFor="file">Select File</Label>
              <div className="flex items-center gap-4">
                <Input
                  id="file"
                  type="file"
                  accept=".pdf,.docx,.doc,.md"
                  onChange={(e) => {
                    const file = e.target.files?.[0] || null;
                    setSelectedFile(file);
                    setValue('file', file);
                  }}
                  disabled={processing || completed}
                />
                {selectedFile && (
                  <div className="flex items-center gap-2 text-sm text-muted-foreground">
                    <FileText className="h-4 w-4" />
                    <span>{selectedFile.name}</span>
                  </div>
                )}
              </div>
              {errors.file && <p className="text-sm text-destructive">{errors.file.message as string}</p>}
            </div>

            {/* Subject Selection */}
            <div className="space-y-2">
              <Label htmlFor="subject">Subject</Label>
              <Select onValueChange={(value) => setValue('subject', value)} disabled={processing || completed}>
                <SelectTrigger>
                  <SelectValue placeholder="Select a subject" />
                </SelectTrigger>
                <SelectContent>
                  {subjects.map((subject) => (
                    <SelectItem key={subject.id} value={subject.name}>
                      {subject.name}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
              {errors.subject && <p className="text-sm text-destructive">{errors.subject.message}</p>}
            </div>

            {/* Folder Selection */}
            <div className="space-y-2">
              <Label htmlFor="folder">Folder</Label>
              <Select
                onValueChange={(value) => setValue('folder', value)}
                disabled={!selectedSubject || processing || completed}
              >
                <SelectTrigger>
                  <SelectValue placeholder="Select a folder" />
                </SelectTrigger>
                <SelectContent>
                  {subjectFolders.map((folder) => (
                    <SelectItem key={folder} value={folder}>
                      {folder}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
              {errors.folder && <p className="text-sm text-destructive">{errors.folder.message}</p>}
            </div>

            {/* Options */}
            <div className="space-y-4 rounded-lg border p-4">
              <h3 className="font-semibold">Processing Options</h3>
              
              <div className="flex items-center space-x-2">
                <Checkbox
                  id="createSummary"
                  checked={createSummary}
                  onCheckedChange={(checked) => setValue('createSummary', checked as boolean)}
                  disabled={processing || completed}
                />
                <label htmlFor="createSummary" className="text-sm font-medium">
                  Create AI Summary
                </label>
              </div>

              <div className="flex items-center space-x-2">
                <Checkbox
                  id="generateQuiz"
                  checked={generateQuiz}
                  onCheckedChange={(checked) => setValue('generateQuiz', checked as boolean)}
                  disabled={processing || completed}
                />
                <label htmlFor="generateQuiz" className="text-sm font-medium">
                  Generate Quiz
                </label>
              </div>

              {generateQuiz && (
                <div className="ml-6 space-y-4 border-l-2 pl-4">
                  <div className="space-y-2">
                    <Label>Number of Questions: {quizQuestions}</Label>
                    <Slider
                      value={[quizQuestions]}
                      onValueChange={(value) => setValue('quizQuestions', value[0])}
                      min={5}
                      max={20}
                      step={1}
                      disabled={processing || completed}
                    />
                  </div>

                  <div className="space-y-2">
                    <Label>Difficulty</Label>
                    <Select
                      onValueChange={(value) => setValue('quizDifficulty', value as 'Easy' | 'Medium' | 'Hard')}
                      disabled={processing || completed}
                    >
                      <SelectTrigger>
                        <SelectValue placeholder="Select difficulty" />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="Easy">Easy</SelectItem>
                        <SelectItem value="Medium">Medium</SelectItem>
                        <SelectItem value="Hard">Hard</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>
                </div>
              )}
            </div>

            {/* Progress */}
            {processing && (
              <div className="space-y-2">
                <div className="flex items-center justify-between text-sm">
                  <span>Processing file...</span>
                  <span>{progress}%</span>
                </div>
                <Progress value={progress} />
              </div>
            )}

            {completed && (
              <div className="flex items-center gap-2 rounded-lg bg-success/10 p-4 text-success">
                <CheckCircle className="h-5 w-5" />
                <span className="font-medium">File processed successfully! Redirecting...</span>
              </div>
            )}

            {/* Submit Button */}
            <Button type="submit" className="w-full" disabled={processing || completed}>
              <UploadIcon className="mr-2 h-4 w-4" />
              {processing ? 'Processing...' : completed ? 'Completed' : 'Upload and Process'}
            </Button>
          </form>
        </CardContent>
      </Card>
    </div>
  );
}
