import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAppStore } from '@/store/useAppStore';
import { toast } from 'sonner';
import { FileUpload } from '@/components/upload/FileUpload';
import { SubjectSelector } from '@/components/upload/SubjectSelector';
import { ProcessingOptions } from '@/components/upload/ProcessingOptions';
import { UploadProgress } from '@/components/upload/UploadProgress';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Upload as UploadIcon, CheckCircle, Loader2 } from 'lucide-react';

export default function Upload() {
  const { subjects, addFile, addSummary, addQuiz } = useAppStore();
  const navigate = useNavigate();
  
  const [selectedFile, setSelectedFile] = useState<File | null>(null);
  const [selectedSubject, setSelectedSubject] = useState<string>('');
  const [createSummary, setCreateSummary] = useState(true);
  const [generateQuiz, setGenerateQuiz] = useState(false);
  const [quizQuestions, setQuizQuestions] = useState(10);
  const [quizDifficulty, setQuizDifficulty] = useState<'Easy' | 'Medium' | 'Hard'>('Medium');
  const [processing, setProcessing] = useState(false);
  const [progress, setProgress] = useState(0);
  const [completed, setCompleted] = useState(false);

  const simulateProcessing = async () => {
    setProcessing(true);
    setProgress(0);

    // Simulate file upload
    for (let i = 0; i <= 100; i += 10) {
      await new Promise((resolve) => setTimeout(resolve, 200));
      setProgress(i);
    }

    setProcessing(false);
    setCompleted(true);
    toast.success('File processed successfully!');

    setTimeout(() => {
      navigate('/summaries');
    }, 2000);
  };

  const handleSubmit = async () => {
    if (!selectedFile) {
      toast.error('Please select a file');
      return;
    }

    if (!selectedSubject) {
      toast.error('Please select a subject');
      return;
    }

    const fileId = `file${Date.now()}`;
    const fileName = selectedFile.name;

    // Add file
    addFile({
      id: fileId,
      name: fileName,
      subject: selectedSubject,
      folder: 'General',
      uploadDate: new Date().toISOString().split('T')[0],
      size: `${(selectedFile.size / 1024 / 1024).toFixed(1)} MB`,
      summaryCount: createSummary ? 1 : 0,
      quizCount: generateQuiz ? 1 : 0,
    });

    // Create summary if requested
    if (createSummary) {
      addSummary({
        id: `sum${Date.now()}`,
        fileId,
        fileName,
        content: 'AI-generated summary of the uploaded document. This content would be generated by the backend processing system analyzing the document content and extracting key information.',
        keyConcepts: ['Concept 1', 'Concept 2', 'Concept 3', 'Concept 4'],
        createdAt: new Date().toISOString().split('T')[0],
        isImportant: false,
      });
    }

    // Generate quiz if requested
    if (generateQuiz) {
      const questions = Array.from({ length: quizQuestions }, (_, i) => ({
        id: `q${Date.now()}_${i}`,
        question: `Sample question ${i + 1} based on ${fileName}`,
        options: ['Option A', 'Option B', 'Option C', 'Option D'],
        correctAnswer: Math.floor(Math.random() * 4),
      }));

      addQuiz({
        id: `quiz${Date.now()}`,
        fileId,
        fileName,
        subject: selectedSubject,
        difficulty: quizDifficulty,
        questions,
        createdAt: new Date().toISOString().split('T')[0],
        completed: false,
      });
    }

    await simulateProcessing();
  };

  return (
    <div className="mx-auto max-w-3xl space-y-6">
      <div>
        <h1 className="text-3xl font-bold">Upload File</h1>
        <p className="text-muted-foreground">Upload your study materials and generate AI summaries and quizzes</p>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>File Upload</CardTitle>
        </CardHeader>
        <CardContent className="space-y-6">
          <FileUpload
            onFileSelect={setSelectedFile}
          />

          <SubjectSelector
            subjects={subjects}
            value={selectedSubject}
            onChange={setSelectedSubject}
            disabled={processing || completed}
          />

          <ProcessingOptions
            createSummary={createSummary}
            onCreateSummaryChange={setCreateSummary}
            generateQuiz={generateQuiz}
            onGenerateQuizChange={setGenerateQuiz}
            quizQuestions={quizQuestions}
            onQuizQuestionsChange={setQuizQuestions}
            quizDifficulty={quizDifficulty}
            onQuizDifficultyChange={setQuizDifficulty}
            disabled={processing || completed}
          />

          {processing && (
            <UploadProgress progress={progress} isCompleted={false} />
          )}

          {completed && (
            <div className="flex items-center gap-2 rounded-lg bg-success/10 p-4 text-success">
              <CheckCircle className="h-5 w-5" />
              <span className="font-medium">File processed successfully! Redirecting...</span>
            </div>
          )}

          <Button
            onClick={handleSubmit}
            className="w-full"
            disabled={processing || completed}
          >
            {processing ? (
              <Loader2 className="mr-2 h-4 w-4 animate-spin" />
            ) : (
              <UploadIcon className="mr-2 h-4 w-4" />
            )}
            {processing ? 'Processing...' : completed ? 'Completed' : 'Upload and Process'}
          </Button>
        </CardContent>
      </Card>
    </div>
  );
}
